import { ReactNode } from "react";

export const metadata = {
  title: "Basejump - Next.js Starter",
  description: "Generated by @usebasejump/cli",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return <>{children}</>;
}
