import Header from "./header";


export const metadata = {
    title: 'Basejump - Next.js Starter',
    description: 'Generated by @usebasejump/cli',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <>
            <Header/>
            {children}
        </>
    )
}
