import './globals.css'

export const metadata = {
    title: 'Basejump - Next.js Starter',
    description: 'Generated by @usebasejump/cli',
}

export default function RootLayout({
                                       children,
                                   }: {
    children: React.ReactNode
}) {
    return (
        <html lang="en">
        <body>
        {children}
        </body>
        </html>
    )
}
